version: '3.6'

services:

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - .:/code
      - ./postgresql/data:/var/lib/postgresql/data

