from .division import DivisionDetailSerializer, DivisionListSerializer, DivisionStaffSerializer, DivisionShortSerializer
from .staff import StaffDetailSerializer, StaffShortSerializer, StaffSubordinatesSerializer
